import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MyAppBar from "../components/MyAppBar"
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyAppBar/>
        <Container maxWidth ="xl">
          <Box sx={{ bgcolor: 'rgb(140,210,210)', height: '100vh'}}>
            {children}
          </Box>
        </Container>
      </body>
    </html>
  );
}
